### ISSUE TITLE
TypeError: invNum.next is not a function

### ISSUE THREAD

**Issue by vanmicky** [amindia/invoice-number#1]
if i run this code :

var invNum = require('invoice-number')
try{
 await invNum.next('sdfsd1')
} catch(e){
console.log("Error")
console.log(e)
}

I will get : TypeError: invNum.next is not a function

**Comment by aaisa** [comment]
Hi @vanmicky I have solved the same problem using V1.0.5 instead of V1.0.6.
I hope this helps you.

**Comment by vanmicky** [comment]
ya thank you i just took the V1.0.5 and it is working well!!! Ty.

**Comment by Pancham97** [comment]
For anybody looking at this in the future, as of `v1.0.6`, you need to use `invNum.InvoiceNumber.next()`.

**Comment by BayoKwendo** [comment]
thanks guys

**Comment by kbala-ami** [comment]
Version 2 Released.
